### ISSUE TITLE
Dealing with introns

### ISSUE THREAD

**Issue by riksub** [cmayer/MitoGeneExtractor#12]
Hi,

I was trying to test the software to extract nuclear coding genes with introns, but apparently, it retrieves only the first open reading frame and misses the rest of the coding gene.
Is there any option to deal with that or is it just out of the target of the software?

R.

**Comment by marievalerie** [comment]
Hi,
how can you extract the first open reading frame?
Or do you mean the first exon of your nuclear gene?

Extracting nuclear genes which have introns is not the target of the software. It might work if you have RNA-seq data (no introns in the reads) and the correctly spliced protein reference, but we never tested it. 

best wishes,
marie
