### ISSUE TITLE
installation

### ISSUE THREAD

**Issue by jbernst** [cmayer/MitoGeneExtractor#3]
Apologies! Can this be deleted? I accidentally submitted an issue here.

Best,
Justin

**Comment by cmayer** [comment]
I just contacted Mrs Brasseur since we should also provide the commands to create the environment from scratch. YML files created on one platform do not necessarily work on another platform.
Maybe you can tell us how you solved your problem. This could save time for other users.

**Comment by cmayer** [comment]
I just verified that we do not provide a yaml file for a conda environment creation. I think we did not do this since it did not work on different platforms. But maybe we should provide the conda command that installs all dependencies for the cutadapt and Snakemake.

**Comment by jbernst** [comment]
Hi,

Yes, that was my mistake! Sorry about that. I was able to get MGE to successfully install. When I installed Exonerate, though, I ran into an error. But updating the base conda environment and channels, followed by rerunning the installation for Exonerate (on the `make` step) worked for me. Thank you for replying!

Best,
Justin

**Comment by cmayer** [comment]
Thanks for your feedback!
Best
Christoph
